name: memory-game-backend
region: fra
domains:
  - domain: memory-api.lorenzboss.com
    type: PRIMARY

services:
  # Backend Service only (Frontend on Vercel)
  - name: backend
    github:
      repo: lorenzboss/m321_memory
      branch: main
      deploy_on_push: true
    source_dir: backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "8000"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FRONTEND_URL
        value: "https://memory.lorenzboss.com"
    cors:
      allow_origins:
        - prefix: https://memory.lorenzboss.com
        - prefix: http://localhost:3000
      allow_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
        - PATCH
      allow_headers:
        - Content-Type
        - Authorization
        - Cookie
        - X-Requested-With
        - Accept
      allow_credentials: true
    health_check:
      http_path: /health
      initial_delay_seconds: 60
