name: memory-game
region: fra

services:
  # Backend Service
  - name: backend
    github:
      repo: lorenzboss/m321_memory
      branch: main
      deploy_on_push: true
    source_dir: /backend
    dockerfile_path: backend/Dockerfile
    http_port: 8000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: "production"
      - key: PORT
        value: "8000"
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: FRONTEND_URL
        value: "${APP_URL}"
    health_check:
      http_path: /health
      initial_delay_seconds: 60

  # Frontend Service
  - name: frontend
    github:
      repo: lorenzboss/m321_memory
      branch: main
      deploy_on_push: true
    source_dir: /frontend
    dockerfile_path: frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: REACT_APP_BACKEND_URL
        value: "${backend.PUBLIC_URL}"
    build_command: npm run build
